apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  selector:
    app: database
  ports:
  - port: 3306
  clusterIP: Nome    
